### ISSUE TITLE
关于“四轮差速底盘”中激光雷达对GNSS天线的信号遮挡问题

### ISSUE THREAD

**Issue by DreamWaterFound** [kahowang/3D-SLAM-Multiple-robot-platforms#1]
十分感谢作者无私分享自己的工作！

我有个问题，在仓库根目录下 [README.md](https://github.com/kahowang/3D-SLAM-Multiple-robot-platforms/blob/5100b54b97e26ac689eec28c18d3346ba114ab68/README.md) 中提到的“四轮差速底盘”，我注意到激光雷达对两台 GNSS 碟状天线的遮挡：

![Screenshot from 2022-08-01 10-09-07](https://user-images.githubusercontent.com/33981288/182058970-b6fcf4c5-f922-43af-9697-a0d5bb9ca619.png)

由于激光雷达和天线距离很近且激光雷达位于天线上方向，附近也有金属支架，在理论上对GNSS定位结果会有不可忽视的劣化。

我想请教下作者，您在实际使用中，GNSS 定位的结果是否有比较明显的跳变现象？如果您有用RTK技术进行高精度定位，想请教下xxGPA语句中的解类型，在室外开阔环境下是否可以保持RTK_FIX呢？

非常期待您的回复！

**Comment by kahowang** [comment]
刘老师你好，我一直都有关注您的知乎工作，对刘老师的工作十分膜拜。谢谢刘老师对我的关注，这个实验平台是我自行在学校搭建的，使用的RTK是星网宇达RTK，你说提到的金属支架和天线位于雷达上方，我个人觉得是有一定影响，之前考虑到车体的位置太局限和尽可能保持雷达的视野，所以只能这样摆放，后续打算放置较小的RTK天线。在测试过程中，在室外开阔(无太大遮挡、高楼)的环境下，是可以保持status：2 (RTK_FIX)的，但在校园内可能高楼较多，有时RTK_FIX会丢失。

**Comment by DreamWaterFound** [comment]
好的好的，非常感谢分享！

**Comment by pedestrain123** [comment]
> 刘老师你好，我一直都有关注您的知乎工作，对刘老师的工作十分膜拜。谢谢刘老师对我的关注，这个实验平台是我自行在学校搭建的，使用的RTK是星网宇达RTK，你说提到的金属支架和天线位于雷达上方，我个人觉得是有一定影响，之前考虑到车体的位置太局限和尽可能保持雷达的视野，所以只能这样摆放，后续打算放置较小的RTK天线。在测试过程中，在室外开阔(无太大遮挡、高楼)的环境下，是可以保持status：2 (RTK_FIX)的，但在校园内可能高楼较多，有时RTK_FIX会丢失。

您好，请问如何进行激光雷达与rtk的外参标定？有什么好的方法推荐吗？
